CLS
PRINT "FLIPFLOP"
PRINT "CREATIVE COMPUTING"
PRINT "MORRISTOWN, NEW JERSEY"
PRINT
REM *** CREATED BY MICHAEL CASS
PRINT "THE OBJECT OF THIS PUZZLE IS TO"
PRINT "CHANGE THIS:"
PRINT
PRINT "X X X X X X X X X X"
PRINT
PRINT "TO THIS:"
PRINT
PRINT "O O O O O O O O O O"
PRINT
PRINT "BY TYPING THE NUMBER CORRESPONDING"
PRINT "TO THE POSITION OF THE LETTER ON SOME"
PRINT "NUMBERS, ONE POSITION WILL CHANGE, ON"
PRINT "OTHERS, TWO WILL CHANGE.  TO RESET LINE"
PRINT "TO ALL X'S, TYPE 0 (ZERO) AND TO START"
PRINT "OVER IN THE MIDDLE OF A GAME, TYPE "
PRINT "11 (ELEVEN)."
PRINT

WAIT KEY

DIM a$(20)

start:

q=RND(1)
CLS
PRINT "HERE IS THE STARTING LINE OF X'S."
PRINT
c=0
turn:
PRINT "1 2 3 4 5 6 7 8 9 10"
PRINT "X X X X X X X X X X"
PRINT

FOR x=1 TO 10
  a$(x)="x"
NEXT x
GOTO enternumber

wrongnumber:
PRINT "ILLEGAL ENTRY--TRY AGAIN."

enternumber:
PRINT "INPUT THE NUMBER: ";
INPUT n

IF n<>INT(n) THEN GOTO wrongnumber
IF n=11 THEN GOTO start
IF n>11 THEN GOTO wrongnumber
IF n=0 THEN GOTO turn
IF m=n THEN GOTO l1
m=n
IF a$(n)="O" THEN GOTO l2
a$(n)="O"
l3:
r=TAN(q+n/q-n)-SIN(q/n)+336*SIN(8*n)
n1=r-INT(r)
n=INT(10*n1)
IF a$(n)="O" THEN GOTO l2
a$(n)="O"
GOTO l4

l2:
a$(n)="X"
IF m=n THEN GOTO l3
GOTO l4

l1:
IF a$(n)="O" THEN GOTO l5
a$(n)="O"
calc:
r=.592*(1/TAN(q/n+q))/SIN(n*2+q)-COS(n)
n1=r-INT(r)
n=INT(10*n1)
IF a$(n)="O" THEN GOTO l5
a$(n)="O"
GOTO l4

l5:
a$(n)="X"
IF m=n THEN GOTO calc

l4:
PRINT "1 2 3 4 5 6 7 8 9 10"
FOR z=1 TO 10
  PRINT a$(z);" ";
NEXT z
c=c+1
PRINT
FOR z=1 TO 10
IF a$(z)<>"O" THEN GOTO enternumber
NEXT z
IF c>12 THEN GOTO l6
PRINT "VERY GOOD.  YOU GUESSED IT IN "
PRINT "ONLY ";c;" GUESSES."
GOTO l7
l6:
PRINT "TRY HARDER NEXT TIME.  IT TOOK"
PRINT "YOU ";c;" GUESSES."
l7:
PRINT "DO YOU WANT TO TRY ANOTHER PUZZLE? ";
INPUT more$
IF LEFT$(more$,1)="N" THEN GOTO end
PRINT
GOTO turn

end:
' Cold Start
SYS $e477

END
